version: '3.7'
services:
  react:
    build:
      args:
        - NODE_VER=16.20.1-slim
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./app:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 5173:5173

volumes:
  node_modules:     
