version: '3.7'
services:
  react:
    build:
      args:
        - NODE_VER=18.17.1-slim
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./app:/home/node/app
    ports:
      - 5173:5173

volumes:
  node_modules:     
